//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARichardsonProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.LoanAccounts = new HashSet<LoanAccount>();
            this.TermAccounts = new HashSet<TermAccount>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AccountID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> StartingBalance { get; set; }
        public Nullable<System.DateTime> EndingBalance { get; set; }
        public Nullable<System.DateTime> AccountOpenDate { get; set; }
        public Nullable<System.DateTime> BeginningStatment { get; set; }
        public Nullable<System.DateTime> NextStatment { get; set; }
        public Nullable<decimal> Balances { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanAccount> LoanAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermAccount> TermAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
