//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARichardsonProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAccount
    {
        public int LoanAccountID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public decimal LoanAmount { get; set; }
        public bool LoanTransfered { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
