//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARichardsonProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermAccount
    {
        public int TermAccountID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public System.DateTime DateOfMaturity { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
